server:
  port: 8089

spring:
  application:
    name: birthday-guardian

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/birthday_guardian?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  mail:
    host: ${SPRING_MAIL_HOST:smtp.163.com}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME:your-email@163.com}
    password: ${SPRING_MAIL_PASSWORD:your-authorization-code}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.birthday.guardian.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: ${JWT_SECRET:birthdayGuardianSecretKeyForHS512AlgorithmMustBeAtLeast64BytesLong2024}
  expiration: ${JWT_EXPIRATION:86400000}

# 定时任务配置
schedule:
  check-time: ${SCHEDULE_CHECK_TIME:0 0 9 * * ?}
